version: "3"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=interview
    volumes:
      - C:\\folder:/var/lib/postgresql/data
  # app:
  #   build: .
  #   container_name: app
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links: 
  #     - database
  #   depends_on:
  #     - database
  #   environment:
  #     - TZ=America/Sao_Paulo

volumes:
  pgdata:
    driver: local